# Compiles the program for Project 2 Hangman++
compile: HangmanBoard.cpp HangmanBoard.h HangmanGame.cpp HangmanGame.h Hangman.cpp
	g++ -Wall -g HangmanBoard.cpp HangmanBoard.h HangmanGame.cpp HangmanGame.h Hangman.cpp -lm -o Hangman

# Runs Program1
run: Program1
	./Hangman

# Clean up!
clean: 
	rm Hangman
