# Compiles the program for Project 3 Menemonics
compile: CS1730Mnemonic.cpp Search.h Search.cpp
	g++ -Wall -g CS1730Mnemonic.cpp Search.h Search.cpp -lm -o CS1730Mnemonic

# Runs CS1730Mnemonics
run: CS1730Mnemonics
	./CS1730Mnemonic

# Clean up!
clean: 
	rm CS1730Mnemonic
