# Compiles the program for Project 6 
GumeShoe_Prae : gcc GumShoe_Prae.c apue.h apue.c -o GumShoe_Prae

# Runs the executable created by make
run: GumeShoe_Prae
	./GumeShoe_Prae

# Clean up!
clean: 
	rm GumeShoe_Prae *.jpg
